<?php
echo '<div class="modal fade" id="taskModal" tabindex="-1" role="dialog">';
		  	echo '<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">';
		    	echo '<div class="modal-content">';
		      	echo '<div class="modal-header">';
		        	echo '<h5 class="modal-title">Modal title</h5>';
		        	echo '<button type="button" class="close" data-dismiss="modal" aria-label="Close">';
		          	echo '<span aria-hidden="true">&times;</span>';
		        	echo '</button>';
		      	echo '</div>';
		      	echo '<div class="modal-body">';
		        	echo '<div class="row justify-content-center">';
		        		echo '<h5><strong>Description</strong></h5>';
		        	echo '</div>';
		        	echo '<div class="row justify-content-center">';
		        		echo '<p>Ceci est la description de la tâche</p>';
		        	echo '</div>';
		        	echo'<hr class="custom-hr">';
		        	echo '<div class="row justify-content-center">';
		        		echo '<p><strong>Project : </strong>Projet #1</p>';
		        	echo '</div>';
		        	echo '<div class="row justify-content-center">';
		        		echo '<p><strong>Deadline : </strong>25/05/2020</p>';
		        	echo '</div>';
		        	echo '<div class="row justify-content-center">';
		        		echo '<div>';
							echo '<p class="inline"><strong>Priority :</strong></p>';
							echo '<div class="inline priority-box priority-high">High</div>';
						echo '</div>';
		        	echo '</div>';
		        	echo '<div class="row justify-content-center">';
	        			echo '<p class="mb-1">Avancement tâches</p>';
	        		echo '</div>';
					echo '<div class="progress mx-auto" style="width:60%;">';
						echo '<div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width:25%;">25%</div>';
					echo '</div>';
					echo '<div class="row justify-content-center mt-2">';
	        			echo '<p class="mb-1">Avancement UserStory</p>';
	        		echo '</div>';
					echo '<div class="progress mx-auto" style="width:60%;">';
						echo '<div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width:25%;">25%</div>';
					echo '</div>';
					echo'<hr class="mt-4 custom-hr">';
					echo '<div class="row justify-content-center mb-2">';
		        		echo '<h5><strong>Participants</strong></h5>';
		        	echo '</div>';
		        	echo '<div class="row justify-content-center">';
		        		echo '<div class="col-4 text-center">';
		        			echo 'Ewan PERRIN';
		        		echo '</div>';
		        		echo '<div class="col-4 text-center">';
		        			echo 'Ewan PERRIN2';
		        		echo '</div>';
		        		echo '<div class="col-4 text-center">';
		        			echo 'Ewan PERRIN3';
		        		echo '</div>';
		        		echo '<div class="col-4 text-center">';
		        			echo 'Ewan PERRIN4';
		        		echo '</div>';
		        	echo '</div>';
		      	echo '</div>';
		      	echo '<div class="modal-footer justify-content-around">';
		        	//echo '<button type="button" class="btn custom-btn">Participer</button>';
		        	echo '<button type="button" class="btn custom-btn"><i class="fas fa-arrow-circle-right"></i>   In Progress</button>';
		        	echo '<button type="button" class="btn custom-btn"><i class="fas fa-arrow-circle-right"></i>   Completed</button>';
		      	echo '</div>';
		    	echo '</div>';
		  	echo '</div>';
		echo '</div>';
		?>